# Generated by Django 5.0.6 on 2024-06-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="example",
            table="apps_example_example",
        ),
    ]
